// src/templates/database/postgres/node/files/apps/frontend/src/App.vue
<!-- forge:dynamic_frontend_integration -->
        <div class="forge-status-box" style="border-color: rgba(59, 130, 246, 0.2);">
          <h2 class="forge-status-title">
            <span class="forge-status-dot" style="background: #3b82f6; box-shadow: 0 0 10px #3b82f6;"></span>
            PostgreSQL
          </h2>
          <div class="forge-status-msg" style="color: #bfdbfe;">
            Relational DB online.
          </div>
        </div>

// src/templates/database/postgres/node/files/apps/frontend/src/App.svelte
<!-- forge:dynamic_frontend_integration -->
      <div class="forge-status-box" style="border-color: rgba(59, 130, 246, 0.2);">
        <h2 class="forge-status-title">
          <span class="forge-status-dot" style="background: #3b82f6; box-shadow: 0 0 10px #3b82f6;"></span>
          PostgreSQL
        </h2>
        <div class="forge-status-msg" style="color: #bfdbfe;">
          Relational DB online.
        </div>
      </div>
