// src/templates/database/mysql/node/files/apps/frontend/src/App.vue
<!-- forge:dynamic_frontend_integration -->
        <div class="forge-status-box" style="border-color: rgba(234, 179, 8, 0.2);">
          <h2 class="forge-status-title">
            <span class="forge-status-dot" style="background: #eab308; box-shadow: 0 0 10px #eab308;"></span>
            MySQL
          </h2>
          <div class="forge-status-msg" style="color: #fef08a;">
            Database connected.
          </div>
        </div>

// src/templates/database/mysql/node/files/apps/frontend/src/App.svelte
<!-- forge:dynamic_frontend_integration -->
      <div class="forge-status-box" style="border-color: rgba(234, 179, 8, 0.2);">
        <h2 class="forge-status-title">
          <span class="forge-status-dot" style="background: #eab308; box-shadow: 0 0 10px #eab308;"></span>
          MySQL
        </h2>
        <div class="forge-status-msg" style="color: #fef08a;">
          Database connected.
        </div>
      </div>
