// src/templates/database/mongodb/node/files/apps/frontend/src/App.vue
<!-- forge:dynamic_frontend_integration -->
        <div class="forge-status-box" style="border-color: rgba(16, 185, 129, 0.2);">
          <h2 class="forge-status-title">
            <span class="forge-status-dot success"></span>
            MongoDB Atlas
          </h2>
          <div class="forge-status-msg text-success">
            Database integrated successfully.
          </div>
        </div>

// src/templates/database/mongodb/node/files/apps/frontend/src/App.svelte
<!-- forge:dynamic_frontend_integration -->
      <div class="forge-status-box" style="border-color: rgba(16, 185, 129, 0.2);">
        <h2 class="forge-status-title">
          <span class="forge-status-dot success"></span>
          MongoDB Atlas
        </h2>
        <div class="forge-status-msg text-success">
          Database integrated successfully.
        </div>
      </div>
