// src/templates/cache/redis/files/apps/frontend/src/App.svelte
<!-- forge:dynamic_frontend_integration -->
      <div class="forge-status-box" style="border-color: rgba(239, 68, 68, 0.2);">
        <h2 class="forge-status-title">
          <span class="forge-status-dot" style="background: #ef4444; box-shadow: 0 0 10px #ef4444;"></span>
          Redis Cache
        </h2>
        <div class="forge-status-msg" style="color: #fecaca;">
          Hot Cache 0.2ms ping.
        </div>
      </div>

// src/templates/cache/redis/files/apps/frontend/src/App.vue
<!-- forge:dynamic_frontend_integration -->
        <div class="forge-status-box" style="border-color: rgba(239, 68, 68, 0.2);">
          <h2 class="forge-status-title">
            <span class="forge-status-dot" style="background: #ef4444; box-shadow: 0 0 10px #ef4444;"></span>
            Redis Cache
          </h2>
          <div class="forge-status-msg" style="color: #fecaca;">
            Hot Cache 0.2ms ping.
          </div>
        </div>
